spring:
  application:
    name: data-synchro

  datasource:
    local:
      url: jdbc:postgresql://localhost:5434/local_store_db
      username: user1
      password: password1
      driver-class-name: org.postgres.Driver
    central:
      url: jdbc:postgresql://localhost:5436/central_store_db
      username: user2
      password: password2
      driver-class-name: org.postgres.Driver

