version: '3.8'

services:
  local_db_server:
    image: postgres:latest
    container_name: local_db_server
    ports:
      - "5434:5432"  # Host port 5434 maps to container port 5432
    environment:
      POSTGRES_DB: local_store_db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    volumes:
      - db1_data:/var/lib/postgresql/data

  central_db_server:
    image: postgres:latest
    container_name: central_db_server
    ports:
      - "5436:5432"  # Host port 5436 maps to container port 5432
    environment:
      POSTGRES_DB: central_store_db
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    volumes:
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data:
